### ISSUE TITLE
bcbio-variation-recall and java version

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio.variation.recall#22]
Hi brad, I see an error on bcbio ensemble variant call because of my openjdk version. 
should I downgrade to openjdk 1.8.0_121 ( where I see no error, or there is reason why  bcbio update openjdk?

Thanks a lot!
Alessandro.
 
bcbio-variation-recall version
Exception in thread "main" java.lang.UnsupportedClassVersionError: bcbio/variation/recall/main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
bash-4.2$ java -version
openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)
OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for the report. Any 1.8.0 build should work fine with bcbio-variation-recall so I don't think the 121 versus 152 change will solve the underlying issue. The error you're seeing typically comes from using an older java 1.7. Is it possible you have `JAVA_HOME` set on your machine? If you do the wrapper script will respect that over using the anaconda installed version. `unset JAVA_HOME` should hopefully fix the problem. If not, it would be helpful to understand where java 1.7 is located on your machine and we can dig more. Thanks much.

**Comment by apastore** [comment]
JAVA_HOME is not set. and I do not have any other java installed . could you tell me where the wrapper script is located? do you have any other suggestion?

Thanks a lot for your help!

-bash-4.2$ java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (Zulu 8.33.0.1-linux64) (build 1.8.0_192-b01)
OpenJDK 64-Bit Server VM (Zulu 8.33.0.1-linux64) (build 25.192-b01, mixed mode)
-bash-4.2$ echo $JAVA_HOME

Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 460, in combine_calls
    return ipython.zip_args(apply(ensemble.combine_calls, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/ensemble.py", line 83, in combine_calls
    callinfo = _run_ensemble_intersection(batch_id, vrn_files, caller_names, base_dir, edata)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/ensemble.py", line 257, in _run_ensemble_intersection
    do.run(cmd, "Ensemble intersection calling: %s" % (batch_id))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/lila/data/abdelwao-lab/pastorea/bcbio/anaconda/bin:$PATH &&  /home/pastore/data/bcbio/anaconda/bin/bcbio-variation-recall ensemble --cores=4 --numpass 2 --names vardict,freebayes,mutect2 --nofiltered /scratch/pastore/tmpclVFqs/I-H-133564-T2-1-D1-1-batch-ensemble.vcf.gz /lila/data/abdelwao-lab/pastorea/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa /lila/data/abdelwao-lab/pastorea/Project/Ross/MRD/MRD/work/ensemble/I-H-133564-T2-1-D1-1-batch/vardict/I-H-133564-T2-1-D1-1-batch-effects-annotated-noeff-nomultiallelic.vcf.gz /lila/data/abdelwao-lab/pastorea/Project/Ross/MRD/MRD/work/ensemble/I-H-133564-T2-1-D1-1-batch/freebayes/I-H-133564-T2-1-D1-1-batch-effects-annotated-filter-noeff-nomultiallelic.vcf.gz /lila/data/abdelwao-lab/pastorea/Project/Ross/MRD/MRD/work/ensemble/I-H-133564-T2-1-D1-1-batch/mutect2/I-H-133564-T2-1-D1-1-batch-effects-annotated-noeff-nomultiallelic.vcf.gz
Exception in thread "main" java.lang.UnsupportedClassVersionError: bcbio/variation/recall/main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
' returned non-zero exit status 1
-bash-4.2$ java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (Zulu 8.33.0.1-linux64) (build 1.8.0_192-b01)
OpenJDK 64-Bit Server VM (Zulu 8.33.0.1-linux64) (build 25.192-b01, mixed mode)
-bash-4.2$ echo $JAVA_HOME

-bash-4.2$ export PATH=/lila/data/abdelwao-lab/pastorea/bcbio/anaconda/bin:$PATH &&  /home/pastore/data/bcbio/anaconda/bin/bcbio-variation-recall
Exception in thread "main" java.lang.UnsupportedClassVersionError: bcbio/variation/recall/main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by apastore** [comment]
I see the problem now. my java is in /home/pastore/data/bcbio/anaconda/bin

but when bcbio-variation-reacall is run , this code set java to /bin/java ( and there is actually a java 1.7 there 

java=java
if [ -e "$JAVA_HOME/bin/java" ]
then
java="$JAVA_HOME/bin/java"
fi

any idea how to fix it?

Thanks!
alessandro

**Comment by chapmanb** [comment]
Alessandro;
Thanks so much for helping track down the problem. Apologies, we'd fixed that empty JAVA_HOME problem in a number of places but missed the wrapper script here. I've pushed a fix in 0.2.3 and am working on updating the bioconda package now. bioconda is a bit stuck on builds because of a problem with CircleCI and OSX builds but as soon as this goes through you should be able to update with `bcbio_nextgen.py upgrade --tools` and get the updated version that won't have this problem. Thanks again.

**Comment by apastore** [comment]
Thanks a lot! Alessandro
